# ===================================================================
# Spring Boot configuration for the "prod" profile.
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/reference/features/profiles.html
# ===================================================================

logging:
  level:
    org.hibernate.sql: info
    com.dct.base: info
    com.dct.nextgen: info
    root: info
  file:
    path: /mnt/logs
    name: ${logging.file.path}/clusterLogData.log # Used by default. Overridden by configuration in logback-spring.xml
  charset:
    console: UTF-8
    file: UTF-8

spring:
  jpa:
    properties:
      hibernate:
        show_sql: false

dct-base:
  domain: http://localhost:8080
  jpa:
    persistence-unit-name: dct-base-persistence
    base-entity-packages:
      - com.dct.base.entity
      - com.dct.nextgen.entity
    base-repository-packages:
      - com.dct.base.repositories
      - com.dct.nextgen.repositories
  datasource:
    database: jdbc:mysql://${NEXTGEN_BRAND_DATABASE_URL};encrypt=true;trustServerCertificate=true
    username: ${NEXTGEN_BRAND_DATABASE_USERNAME}
    password: ${NEXTGEN_BRAND_DATABASE_PASSWORD}
  security:
    auth:
      base64-secret-key: ${NEXTGEN_BRAND_SECRET_KEY}
      # Token is valid 24 hours
      token-validity: 86400000 # milliseconds
      token-validity-for-remember-me: 86400000 # milliseconds