# ===================================================================
# Spring Boot configuration for the "dev" profile.
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/reference/features/profiles.html
# ===================================================================

logging:
  level:
    com.dct.base: debug
    com.dct.nextgen: debug
    root: debug
  charset:
    console: UTF-8
    file: UTF-8

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true

dct-base:
  domain: http://localhost:8080
  jpa:
    persistence-unit-name: dct-base-persistence
    base-entity-packages:
      - com.dct.base.entity
      - com.dct.nextgen.entity
    base-repository-packages:
      - com.dct.base.repositories
      - com.dct.nextgen.repositories
  datasource:
    database: jdbc:mysql://localhost:3306/nextgen_brand?serverTimezone=UTC
    username: admin-nextgen-brand
    password: 123456a@
  security:
    auth:
      base64-secret-key: ZGN0X2Jhc2Vfc2VjcmV0X2tleV90b2tlbi12YWxpZGl0eV84NjQwMDAwMG1zX2Zvcl9yZW1lbWJlcl9tZV84NjQwMDAwMG1z
      # Token is valid 24 hours
      token-validity: 86400000 # milliseconds
      token-validity-for-remember-me: 86400000 # milliseconds
